; AMAZE ini file


[MainSettings]
; Path to where the population models are living. Models should be stored
; in hdf5 format, with the channel as the base group, and model parameters
; as subgroups (e.g., 'CE/chi01/alpha0.5').
; This should point to the population models available here: https://zenodo.org/record/4277620#.X7w28RNKjUI 
path-to-populations = models_reduced.hdf5

; Stem for all output files. If missing of None, will not include an
; extra file stem.
output-name = None

; Sets the 'true' model from which mock observations are drawn. Needs to have
; the same number of entries as the number of keys in the 'population-parameters'
; argument. If None or missing, will assume that you are inferring the true
; parameters using observations.
true-model = None

; Dict that specifies which event-level parameters to use in the inference.
; Keys should match the names of the series in the population model data,
; 'limits' specify the bounds to be used for each parameter which is
; necessary to properly rescale the multi-dimensional density estimates
; to a unit cube, and 'fullname' is used for plotting purposes.
event-parameter-dict = {
    'mchirp' : {'limits':(0,100), 'fullname':'Chirp Mass [$M_\\odot$]'},
    'q' : {'limits':(0,1), 'fullname':'Mass Ratio'},
    'chieff' : {'limits':(-1,1), 'fullname':'Effective Inspiral Spin'},
    'z' : {'limits':(0,2), 'fullname':'Redshift'},
    }

; Dict that specifies the population-level parameters used in the inference.
; The keys in the 'values' sub-dictionary should match the keys in the h5 file
; for each population variation. The items in the 'values' dictionary map the
; names of each sub-population to the value of the hyperparameter.
; If 'transform' is 'log' for a hyperparmeter, the training and continuous sampling
; of the normalising flow is done in log space of that hyperparameter.
population-parameter-dict = {
    'chib' : {'values':{'chi00':0.0, 'chi01':0.1, 'chi02':0.2, 'chi05':0.5},
        'fullname':'$\\chi_\\mathrm{birth}$',
        'transform':'linear'},
    'alphaCE' : {'values':{'alpha02':0.2, 'alpha05':0.5, 'alpha10':1.0, 'alpha20':2.0, 'alpha50':5.0},
        'fullname':'$\\alpha_\\mathrm{CE}$',
        'transform':'log'}
    }

; Dict that specifies which astrophysical channels are being considered in
; the inference. Keys of this dictionary should match the keys in the h5
; population file. 'parameters' specifies which population hyperparameters
; are varied for each population model.
channels-dict = {
    'CE':  {'parameters':['chib','alphaCE'], 'fullname':'Common Envelope'},
    'CHE': {'parameters':['chib'], 'fullname':'Chemically Homogeneous Evolution'},
    'GC':  {'parameters':['chib'], 'fullname':'Globular Clusters'},
    'NSC': {'parameters':['chib'], 'fullname':'Nuclear Star Clusters'},
    'SMT': {'parameters':['chib'], 'fullname':'Stable Mass Transfer'}
    }

; Boolean argument to determine whether to use normalising flows to estimate
; hyperlikelihoods in inference. Otherwise, KDEs will be used.
use-flows = True

; Boolean argument to determine whether hyperparameter inference should be
; done on a continuous range (True) or discretely at the locations of the
; training models (False). Continuous inference can only be performed if
; use-flows is True.
continuous-sampling = True


[RealObservations]
; Path where observational samples live. Must be set if not using mock
; observations in the analysis.
; This should point to the pre-processed GWTC-3 events, available here: https://zenodo.org/records/14967688. 
event-samples-path = /GWTC-3/events

; Key for the series that contains prior evaluations for the event-level
; posterior samples, which needs to be divided out when performing
; hierarchical inference. If None, will assume that the priors are
; already divided out for the samples in 'event-samples-path' (i.e., this
; file contains samples from the likelihood.
event-level-prior = p_theta_jcb

; Can specify a list of events that you wish to exclude
; Do not include file type string (e.g., .hdf5)
events-to-exclude = None

[MockObservations]
; Dict that specifies underlying branching fractions of each channel for
; the injected model when using mock observations. Values must sum to unity.
branching-fractions = {
    'CE'  : 0.2,
    'CHE' : 0.2,
    'GC'  : 0.2,
    'NSC' : 0.2,
    'SMT' : 0.2
    }
;branching-fractions = None

; Specifies how to mock up measurement uncertainties for mock observations.
; Available options are:
; 'delta': assumes a single sample taken at the true value
; 'snr': assumes Gaussian-distributed likelihood with a SNR-dependent sigma
; 'events': assumes Gaussian with sigma taken from average spread from observed events
mock-uncertainty = events
;mock-uncertainty = None

; Number of mock observations to be taken from the mixture model.
n-observations = 20
;n-observations = None

; String that contains detection probabilities for each sample: 'pdet_${sensitivity-key}'
; These weights are used when drawing observed samples from the underlying
; population models, and for determining the detection efficiency.
; If None, will assume that all systems are detectable.
; NOTE: If there are cosmological weights for the population model as well,
; supply these in the dataframe using series called 'weight'
; NOTE: If using 'snr' mock uncertainty, will also need to supply optimal SNRs with the 
; same key in the format 'snropt_${sensitivity-key}'
sensitivity-key = midhighlatelow_network

; Boolean to determine whether to draw mock observations probabilistically based on
; using random number generator and the supplied branching fractions. This will lead
; to the branching fractions not being exactly equal to the supplied values. If set
; to False, code will do the best rounding it can based on the input branching
; fractions if not perfectly divisible.
probabilistic-draws = False

[Flows]
; File name used for saving/loading flow models. If this model already exists,
; the already-trained model can be loaded in if 'train-flows' = False.
; The trained normalising flows used in the paper may be used instead of training new flows, 
; by pointing the `flow-model-path` input to the flow models available here: https://zenodo.org/records/14967688
; and setting `train-flows` to False. 
flow-model-path = flow_models

; Boolean that determines whether to train new flows (True) or to load in
; pre-existing flow model (False).
train-flows = True

; Dictionary that specifies parameters that are used in training the flows for.
; each formation channel.
flow-settings = {
    'CE'  : {'learning-rate' : 0.001,
            'epochs' : 15000,
            'spline-bins' : 5,
            'N-transformations' : 6,
            'N-neurons' : 128,
            'N-blocks' : 2
        },
    'CHE' : {'learning-rate' : 0.001,
            'epochs' : 10000,
            'spline-bins' : 4,
            'N-transformations' : 6,
            'N-neurons' : 128,
            'N-blocks' : 2
        },
    'GC'  : {'learning-rate' : 0.001,
            'epochs' : 10000,
            'spline-bins' : 4,
            'N-transformations' : 6,
            'N-neurons' : 128,
            'N-blocks' : 2
        },
    'NSC' : {'learning-rate' : 0.001,
            'epochs' : 10000,
            'spline-bins' : 5,
            'N-transformations' : 6,
            'N-neurons' : 128,
            'N-blocks' : 2
        },
    'SMT' : {'learning-rate' : 0.001,
            'epochs' : 10000,
            'spline-bins' : 4,
            'N-transformations' : 6,
            'N-neurons' : 128,
            'N-blocks' : 2
        }
    }

; Number of batches used to train flow models.
n-batches = 10000

; Device to run the inference on when using flows. Default is 'cpu'. When
; using GPU, should write 'cuda:X' where X is the slot of the GPU
device = cuda:0


[Sampler]
; Number of walkers (emcee ensemble sampler)
n-walkers = 250

; Number of steps (emcee ensemble sampler)
n-steps = 1000

; Burn-in fraction (emcee ensemble sampler)
f-burnin = 0.4


[ExtraOptions]
; Boolean to determine verbosity
verbose = True

; Boolean to determine whether to make diagnostic plots during the inference.
make-plots = False

; Sets random seed
random-seed = 12

; Number of samples to be drawn from the event posterior distributions. Increasing
; this will increase computation time since these posteriors all need to be frozen
; in the population models.
n-samples = 11058

; If not None, will be used at the N in the regularization during inference
n-regularization = 990903

; Set spin magnitude distribution to be used in the inference if spin
; magnitudes are not specified in the population models.
; Available options are: 'uniform', 'isotropic'.
spin-mag-distribution = uniform

; Fixed parameters to use for making marginalized KDEs if model0=None
marg-kde-fixed-params = {'chib':'chi00', 'alphaCE':'alpha10'}

; Determine number of processesors used for multithreading the freezing of samples
; in the KDE models and drawing samples from the underlying distributions in mock
; observations.
; FIXME: multithreading is not working yet
multiproc-kde = False

; Set max number of samples to use when construction the KDEs.
; if None, will use default value of 1e5
kde-max-samples = None

; Set bandwidth of the KDEs.
; if None, will use default value of 0.01
kde-bandwidth = None